.github/workflows/main.yml
website/src/main/java/bbeb/website/config/security/WebSecurityConfig.java

- [x ] 기능 추가 ✨
root 경로 접속시 swagger로 접속하도록 변경했습니다.

✨Feature/swagger adress/#32

---

website/src/main/java/bbeb/website/config/QuerydslConfig.java

- [x ] 코드 형태 개선 🎨
QuerydslConfig 파일 패키지 이동

🎨docs: Move QuerydslConfig.java

---

website/build.gradle
website/src/main/java/bbeb/website/WebsiteApplication.java
website/src/main/java/bbeb/website/config/exception/CustomAuthenticationEntryPoint.java
website/src/main/java/bbeb/website/config/exception/CustomException.java
website/src/main/java/bbeb/website/config/exception/ErrorCode.java
website/src/main/java/bbeb/website/config/exception/ErrorResponse.java
website/src/main/java/bbeb/website/config/exception/GlobalExceptionHandler.java
website/src/main/java/bbeb/website/config/security/WebSecurityConfig.java
website/src/main/java/bbeb/website/config/security/jwt/JwtAuthenticationFilter.java
website/src/main/java/bbeb/website/config/security/jwt/JwtExceptionFilter.java
website/src/main/java/bbeb/website/config/security/jwt/JwtTokenProvider.java
website/src/main/java/bbeb/website/controller/AuthController.java
website/src/main/java/bbeb/website/dto/AuthDTO.java
website/src/main/java/bbeb/website/repository/MemberRepositoryCustom.java
website/src/main/java/bbeb/website/repository/MemberRepositoryImpl.java
website/src/main/java/bbeb/website/service/AuthService.java

- [ x] 기능 추가 ✨
CustomException 추가

✨Feature/exception/#38

---

client/src/component/header.js
client/src/page/Board/post.js
client/src/page/Profile/Profile.js
client/src/theme.js

헤더 컴포넌트와 프로필, 게시글 페이지의 요소 크기 단위를 px에서 비율로 수정했습니다.
😍😍😍😍😍

🎨36 코드 리팩토링

---

client/src/component/authModal_fail.js
client/src/component/authModal_success.js
client/src/component/header.js
client/src/component/login.js
client/src/component/register.js

login.js, register.js, AuthModalFail, AuthModalSuccess 코드 레이아웃 깨지는것을 방지하기 위해 px에서 퍼센트로 바꿨습니다! 코드 상에서 이상하게 먹히거나 또는 안먹히는 부분(boxShadow, borderRadiuse 등)은 그대로 px로 두었습니다!!
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
1. 비밀번호 텍스트 필드에서 보통은 *이렇게 안보이게 숨겨주는데 지금은 다음과 같이 되어있습니다.
비밀번호 안보이게끔 수정할까요??
2. 피그마랑 다른점
첫번째가 제가 구현한 부분이고 두번째가 피그마에서 디자인한건데 에러문구를 가져왔기때문에 문구가 다릅니다.(의미는 똑같습니다.) 이 부분 수정해야할까요?

🎨 로그인 및 회원가입(+모달창) 레이아웃 수정

---

website/src/main/java/bbeb/website/config/SwaggerConfig.java
website/src/main/java/bbeb/website/controller/CommentController.java
website/src/main/java/bbeb/website/domain/comment/Comment.java
website/src/main/java/bbeb/website/domain/comment/CommentType.java
website/src/main/java/bbeb/website/domain/member/Member.java
website/src/main/java/bbeb/website/domain/post/Post.java
website/src/main/java/bbeb/website/dto/CommentDTO.java
website/src/main/java/bbeb/website/dto/PostDTO.java
website/src/main/java/bbeb/website/repository/comment/CommentRepository.java
website/src/main/java/bbeb/website/repository/comment/CommentRepositoryCustom.java
website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
website/src/main/java/bbeb/website/repository/member/ProfileRepository.java
website/src/main/java/bbeb/website/repository/post/content/ContentRepository.java
website/src/main/java/bbeb/website/repository/post/post/PostRepository.java
website/src/main/java/bbeb/website/repository/post/post/PostRepositoryCustom.java
website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
website/src/main/java/bbeb/website/repository/post/postlike/PostLikeRepository.java
website/src/main/java/bbeb/website/repository/post/postlike/PostLikeRepositoryCustom.java
website/src/main/java/bbeb/website/repository/post/postlike/PostLikeRepositoryImpl.java
website/src/main/java/bbeb/website/repository/post/tag/PostTagRepository.java
website/src/main/java/bbeb/website/repository/post/tag/PostTagRepositoryCustom.java
website/src/main/java/bbeb/website/repository/post/tag/PostTagRepositoryImpl.java
website/src/main/java/bbeb/website/repository/post/tag/TagRepository.java
website/src/main/java/bbeb/website/service/CommentService.java
website/src/main/java/bbeb/website/service/MemberService.java
website/src/main/java/bbeb/website/service/PostService.java

✨feat: #55 Add post comment

---

website/src/main/java/bbeb/website/domain/comment/Comment.java
website/src/main/java/bbeb/website/domain/comment/CommentType.java
website/src/main/java/bbeb/website/dto/CommentDTO.java
website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
website/src/main/java/bbeb/website/service/CommentService.java

- [x ] 기능 추가 ✨
현재 댓글은 이모티콘 또는 댓글만 작성 가능한데 둘 다 나오게 변경

✨Feature/comment#55

---

website/src/main/java/bbeb/website/config/SwaggerConfig.java
website/src/main/java/bbeb/website/config/exception/ErrorCode.java
website/src/main/java/bbeb/website/controller/CharacterController.java
website/src/main/java/bbeb/website/domain/character/CharacterLike.java
website/src/main/java/bbeb/website/domain/character/MainCharacter.java
website/src/main/java/bbeb/website/domain/member/Member.java
website/src/main/java/bbeb/website/dto/VoteDTO.java
website/src/main/java/bbeb/website/repository/character/character/CharacterRepository.java
website/src/main/java/bbeb/website/repository/character/character/CharacterRepositoryCustom.java
website/src/main/java/bbeb/website/repository/character/character/CharacterRepositoryImpl.java
website/src/main/java/bbeb/website/repository/character/characterlike/CharacterLikeRepository.java
website/src/main/java/bbeb/website/service/CharacterService.java
website/src/main/java/bbeb/website/util/scheduler/VoteScheduler.java

✨feat: #57 Add vote system

---

client/src/page/Board/post.js

게시글 백엔드 통신
/post
51번째 줄부터 게시글 데이터 get 요청 코드인데 자꾸 null 값으로 떠서 주석처리 해놓고 31번째 줄에 임시로 객체 만들었습니다ㅠㅠ 따봉은 잘 되는데 게시글 데이터는 왜 그러는지 모르겠어요

✨ 게시글 백엔드 통신

---

website/src/main/java/bbeb/website/config/exception/ErrorCode.java
website/src/main/java/bbeb/website/config/exception/ErrorResponse.java
website/src/main/java/bbeb/website/controller/AuthController.java
website/src/main/java/bbeb/website/controller/CharacterController.java
website/src/main/java/bbeb/website/controller/CommentController.java
website/src/main/java/bbeb/website/controller/MemberController.java
website/src/main/java/bbeb/website/controller/PostController.java
website/src/main/java/bbeb/website/controller/TetrisScoreController.java
website/src/main/java/bbeb/website/dto/AuthDTO.java
website/src/main/java/bbeb/website/dto/CommentDTO.java
website/src/main/java/bbeb/website/dto/PostDTO.java
website/src/main/java/bbeb/website/dto/ProfileDTO.java
website/src/main/java/bbeb/website/dto/TetrisScoreDTO.java
website/src/main/java/bbeb/website/dto/TokenDTO.java
website/src/main/java/bbeb/website/dto/VoteDTO.java
website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
website/src/main/java/bbeb/website/service/AuthService.java
website/src/main/java/bbeb/website/service/CharacterService.java
website/src/main/java/bbeb/website/service/CommentService.java
website/src/main/java/bbeb/website/service/MemberService.java
website/src/main/java/bbeb/website/service/PostService.java
website/src/main/java/bbeb/website/service/TetrisScoreService.java

✨Feature/docs/#75

---

client/src/page/Ranking/Ranking.js

✨ 인기 투표 순위 백엔드 통신

---

website/src/main/java/bbeb/website/controller/CommentController.java
website/src/main/java/bbeb/website/dto/CommentDTO.java
website/src/main/java/bbeb/website/dto/PostDTO.java
website/src/main/java/bbeb/website/repository/comment/CommentRepositoryCustom.java
website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
website/src/main/java/bbeb/website/service/CommentService.java
website/src/main/java/bbeb/website/service/PostService.java

- [ x] 기능 추가 ✨
게시글/댓글에서 수정/삭제 권한 업데이트 했습니다.

✨feat: #83 Add update/delete Auth

---

website/src/main/java/bbeb/website/repository/post/postview/PostViewRepository.java
website/src/main/java/bbeb/website/service/PostService.java

🐛fix: #85 Fix delete error

---

client/src/page/Board/post.js

게시물 삭제 기능
작성자에게만 게시물 삭제|수정 버튼 보이게
작성 날짜 예쁘게
아직 페이지가 merge되지않아 삭제 시 메인 페이지로 이동하게 했습니다.

✨ 게시물 삭제 기능 등등

---

website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java

- [ x] 버그 수정 🐛
페이징 제대로 안 되는 거 수정 했습니다.

🐛fix: #91 Page error fix

---

website/src/main/java/bbeb/website/domain/comment/Comment.java
website/src/main/java/bbeb/website/dto/CommentDTO.java
website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java

✨fix: #94 Modify emoticon

---

website/src/main/java/bbeb/website/dto/PostDTO.java

🎨fix: #104 refactor code

---

website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
website/src/main/java/bbeb/website/service/PostService.java

- [ x ] 기능 추가 ✨
공지된 글 정렬 우선순위 추가

✨feat: #106 Add Pinned post Priority

---

client/src/App.js
client/src/page/Board/post.js

✨postId에 따라 주소 입력

---

client/src/component/comment.js

✨게시글에 맞는 댓글 불러오기

---

client/src/App.js
client/src/page/Write/writeUpdate.js

게시글을 수정할 수 있는 기능을 넣었습니다!
postId를 831로 고정시켜놓고 확인했을땐 잘되는데, 코드를 동적으로 바꿨을때 잘되는지는 모르겠어요!
이 부분 확인 한번 부탁드립니다!

✨ 게시글 수정 기능
